services:
  postgres:
    image: postgres:13.3
    container_name: postgresql
    restart: always
    environment:
      POSTGRES_DB: project 
      POSTGRES_USER: fiveret
      POSTGRES_PASSWORD: Alinochka2005
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  core-service:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - postgres
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgsadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - postgres

volumes:
  postgres_data:
    driver: local